/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // useCasesSideBar: [{ type: "autogenerated", dirName: "." }],
  useCasesSideBar: [
    {
      type: "category",
      label: "Use cases",
      link: {
        type: "doc",
        id: "index",
      },
      items: [
        "credit-profile-widget",
        "embedded-funding-search",
        "native-funding-search",
        "direct-referral",
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
